service: cloud-chat
frameworkVersion: "3"
configValidationMode: error

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dynamodb-local

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    platform: node
    target: node20
    format: esm
    outputFileExtension: .mjs
    concurrency: 10
    exclude: "@aws-sdk/*"
    define:
      require.resolve: undefined
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  deploymentMethod: direct
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminGetUser
          Resource: !GetAtt CloudChatUserPool.Arn
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: !GetAtt CloudChatTable.Arn
  httpApi:
    authorizers:
      CloudChatAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt CloudChatUserPool.ProviderURL
        audience:
          - !Ref CloudChatUserPoolClient
  environment:
    COGNITO_CLIENT_ID: !Ref CloudChatUserPoolClient
    COGNITO_POOL_ID: !Ref CloudChatUserPool

functions:
  sign-up:
    handler: src/functions/sign-up.handler
    events:
      - httpApi:
          path: /auth/sign-up
          method: post
  account-confirmation:
    handler: src/functions/account-confirmation.handler
    events:
      - httpApi:
          path: /auth/account-confirmation
          method: post
  sign-in:
    handler: src/functions/sign-in.handler
    events:
      - httpApi:
          path: /auth/sign-in
          method: post
  refresh-token:
    handler: src/functions/refresh-token.handler
    events:
      - httpApi:
          path: /auth/refresh-token
          method: post
  forgot-password:
    handler: src/functions/forgot-password.handler
    events:
      - httpApi:
          path: /auth/forgot-password
          method: post
  reset-password:
    handler: src/functions/reset-password.handler
    events:
      - httpApi:
          path: /auth/reset-password
          method: post
  profile:
    handler: src/functions/profile.handler
    events:
      - httpApi:
          path: /profile
          method: get
          authorizer:
            name: CloudChatAuthorizer

resources:
  Resources:
    CloudChatTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: cloud-chat
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: key
            KeyType: RANGE

    CloudChatSmsRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - cognito-idp.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: CloudChatSmsRolePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - sns:Publish
                  Resource: "*"

    CloudChatUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: cloud-chat-user-pool
        MfaConfiguration: OFF
        DeletionProtection: ACTIVE
        UsernameAttributes:
          - phone_number
        AutoVerifiedAttributes:
          - phone_number
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_phone_number
              Priority: 1
        SmsConfiguration:
          SnsCallerArn: !GetAtt CloudChatSmsRole.Arn
          ExternalId: !Ref AWS::AccountId
          SnsRegion: !Ref AWS::Region
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        Schema:
          - AttributeDataType: String
            Name: phone_number
            Required: true
            Mutable: true
          - AttributeDataType: String
            Name: name
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
            TemporaryPasswordValidityDays: 1

    CloudChatUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: cloud-chat-user-pool-client
        UserPoolId: !Ref CloudChatUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        TokenValidityUnits:
          AccessToken: days
          RefreshToken: days
        AccessTokenValidity: 1
        RefreshTokenValidity: 1
